In [3]:
#En este entorno virtual .venv, ya estan todas las cosas que necesito, pues las descargue para el labo anterior.
#Solo necesito importar
from sqlalchemy import create_engine
# Import the 'prettytable' library, which is used to display data in a formatted table
import prettytable
#para obtener el password de las environment variables
import os
# Load environment variables from .env file
from dotenv import load_dotenv
load_dotenv()
#para manipular data y llenar las tablas en sql
import pandas as pd

# Set the default display format for prettytable to 'DEFAULT' (i.e., a simple table format)
prettytable.DEFAULT = 'DEFAULT'
#cargo la extension para poder hacer magic commands
%load_ext sql

### El proyecto
Vamos a usar las tablas de chicago del labo anterior, la de los datos socioeconomicos de chicago, y la de los datos de las escuelas.
Ademas, vamos a usar otra tabla, relacionada con los crimenes en chicago.
Es claro que no conviene crear un nuevo dataset en sqlite como sugiere el notebook de los profes, sino que conviene conectarme
al dataset 'chicago' que cree en postgres en el labo anterior, y crear esta nueva tabla de crimenes que me falta

In [5]:
#me conecto al database chicago
psql_psw = os.getenv("PSQL_PSW")
DATABASE_URL_chicago = f"postgresql://root:{psql_psw}@127.0.0.1:5432/chicago"

try:
    engine_chicago = create_engine(DATABASE_URL_chicago)
    conn_chicago = engine_chicago.connect()
    print(f"Connected successfully to {DATABASE_URL_chicago}!")
except Exception as e:
    print(f"Connection to {DATABASE_URL_chicago} failed:", e)

Connected successfully to postgresql://root:toor@127.0.0.1:5432/chicago!

### Creacion y llenado de la nueva tabla 'chicago_crime_data'

In [3]:
data = "https://data.cityofchicago.org/resource/ijzp-q8t2.csv"

df = pd.read_csv(data)
df.to_sql("chicago_crime_data", conn_chicago, if_exists='replace', index=False)

1000

NOTA: La tabla tiene muchas mas filas en realidad que 1000, tiene 8258495, pero la API tiene como limite 1000 filas. Puedo superar esto descargando
el .csv, pero para mis fines educativos 1000 filas son suficientes

### Analisis exploratorio de las tablas en el dataset 'chicago'

In [6]:
#antes que nada, preparo el magic command sql con este database
%sql $DATABASE_URL_chicago

In [7]:
#veo las tablas en este database
tablas = %sql SELECT tablename FROM pg_catalog.pg_tables WHERE schemaname = 'public';
print(tablas)

 * postgresql://root:***@127.0.0.1:5432/chicago
3 rows affected.
+----------------------------+
|         tablename          |
+----------------------------+
| chicago_socioeconomic_data |
|       school_chicago       |
|     chicago_crime_data     |
+----------------------------+

Efectivamente estan las 3 tablas que necesitamos, las dos del labo anterior y la nueva que recien agregue.

In [8]:
#exploro las propiedades de las tablas en el database
for tabla in tablas:
    query = f"SELECT column_name, data_type, is_nullable, column_default FROM information_schema.columns WHERE table_name = '{tabla[0]}'";
    res = %sql $query
    print(tabla[0])
    print(res)

 * postgresql://root:***@127.0.0.1:5432/chicago
9 rows affected.
chicago_socioeconomic_data
+---------------------------------------------+------------------+-------------+----------------+
|                 column_name                 |    data_type     | is_nullable | column_default |
+---------------------------------------------+------------------+-------------+----------------+
|                hardship_index               | double precision |     YES     |      None      |
|                      ca                     | double precision |     YES     |      None      |
|          percent_of_housing_crowded         | double precision |     YES     |      None      |
|       percent_households_below_poverty      | double precision |     YES     |      None      |
|          percent_aged_16_unemployed         | double precision |     YES     |      None      |
| percent_aged_25_without_high_school_diploma | double precision |     YES     |      None      |
|       percent_aged_under_18_or_over_64      | double precision |     YES     |      None      |
|              per_capita_income_             |      bigint      |     YES     |      None      |
|             community_area_name             |       text       |     YES     |      None      |
+---------------------------------------------+------------------+-------------+----------------+
 * postgresql://root:***@127.0.0.1:5432/chicago
79 rows affected.
school_chicago
+---------------------------------------------------+------------------+-------------+----------------+
|                    column_name                    |    data_type     | is_nullable | column_default |
+---------------------------------------------------+------------------+-------------+----------------+
|                      zip_code                     |      bigint      |     YES     |      None      |
|                 environment_score                 | double precision |     YES     |      None      |
|                    safety_score                   | double precision |     YES     |      None      |
|                 instruction_score                 | double precision |     YES     |      None      |
|                isat_exceeding_math_               | double precision |     YES     |      None      |
|              isat_exceeding_reading_              | double precision |     YES     |      None      |
|                isat_value_add_math                | double precision |     YES     |      None      |
|                isat_value_add_read                | double precision |     YES     |      None      |
|             average_student_attendance            | double precision |     YES     |      None      |
|       rate_of_misconducts_per_100_students_       | double precision |     YES     |      None      |
|       college_enrollment_number_of_students_      |      bigint      |     YES     |      None      |
|              general_services_route_              |      bigint      |     YES     |      None      |
|             average_teacher_attendance            | double precision |     YES     |      None      |
|                     rcdts_code                    |      bigint      |     YES     |      None      |
|                    x_coordinate                   | double precision |     YES     |      None      |
|                    y_coordinate                   | double precision |     YES     |      None      |
|                      latitude                     | double precision |     YES     |      None      |
|                     longitude                     | double precision |     YES     |      None      |
|               community_area_number               |      bigint      |     YES     |      None      |
| individualized_education_program_compliance_rate_ | double precision |     YES     |      None      |
|                        ward                       |      bigint      |     YES     |      None      |
|                  police_district                  |      bigint      |     YES     |      None      |
|                     school_id                     |      bigint      |     YES     |      None      |
|                   teachers_score                  |       text       |     YES     |      None      |
|              parent_engagement_icon_              |       text       |     YES     |      None      |
|              parent_engagement_score              |       text       |     YES     |      None      |
|              parent_environment_icon              |       text       |     YES     |      None      |
|              parent_environment_score             |       text       |     YES     |      None      |
|                   pk_2_literacy                   |       text       |     YES     |      None      |
|                     pk_2_math_                    |       text       |     YES     |      None      |
|               gr3_5_grade_level_math              |       text       |     YES     |      None      |
|              gr3_5_grade_level_read_              |       text       |     YES     |      None      |
|               gr3_5_keep_pace_read_               |       text       |     YES     |      None      |
|                gr3_5_keep_pace_math               |       text       |     YES     |      None      |
|               gr6_8_grade_level_math              |       text       |     YES     |      None      |
|               gr6_8_grade_level_read              |       text       |     YES     |      None      |
|                gr6_8_keep_pace_math               |       text       |     YES     |      None      |
|                gr6_8_keep_pace_read               |       text       |     YES     |      None      |
|                 gr_8_explore_math                 |       text       |     YES     |      None      |
|                 gr_8_explore_read                 |       text       |     YES     |      None      |
|             isat_value_add_color_math             |       text       |     YES     |      None      |
|             isat_value_add_color_read             |       text       |     YES     |      None      |
|              students_taking_algebra              |       text       |     YES     |      None      |
|              students_passing_algebra             |       text       |     YES     |      None      |
|              _th_grade_explore_2009_              |       text       |     YES     |      None      |
|              _th_grade_explore_2010_              |       text       |     YES     |      None      |
|                _th_grade_plan_2009_               |       text       |     YES     |      None      |
|                _th_grade_plan_2010_               |       text       |     YES     |      None      |
|            net_change_explore_and_plan            |       text       |     YES     |      None      |
|            _th_grade_average_act_2011_            |       text       |     YES     |      None      |
|              net_change_plan_and_act              |       text       |     YES     |      None      |
|                college_eligibility_               |       text       |     YES     |      None      |
|                  graduation_rate_                 |       text       |     YES     |      None      |
|              college_enrollment_rate              |       text       |     YES     |      None      |
|               freshman_on_track_rate              |       text       |     YES     |      None      |
|                community_area_name                |       text       |     YES     |      None      |
|                      location                     |       text       |     YES     |      None      |
|                   name_of_school                  |       text       |     YES     |      None      |
|             elementary_or_high_school             |       text       |     YES     |      None      |
|                   street_address                  |       text       |     YES     |      None      |
|                        city                       |       text       |     YES     |      None      |
|                       state                       |       text       |     YES     |      None      |
|                    phone_number                   |       text       |     YES     |      None      |
|                       link_                       |       text       |     YES     |      None      |
|                  network_manager                  |       text       |     YES     |      None      |
|                 collaborative_name                |       text       |     YES     |      None      |
|           adequate_yearly_progress_made_          |       text       |     YES     |      None      |
|                   track_schedule                  |       text       |     YES     |      None      |
|           cps_performance_policy_status           |       text       |     YES     |      None      |
|            cps_performance_policy_level           |       text       |     YES     |      None      |
|             healthy_schools_certified_            |       text       |     YES     |      None      |
|                    safety_icon_                   |       text       |     YES     |      None      |
|              family_involvement_icon              |       text       |     YES     |      None      |
|              family_involvement_score             |       text       |     YES     |      None      |
|                 environment_icon_                 |       text       |     YES     |      None      |
|                 instruction_icon_                 |       text       |     YES     |      None      |
|                   leaders_icon_                   |       text       |     YES     |      None      |
|                   leaders_score_                  |       text       |     YES     |      None      |
|                   teachers_icon_                  |       text       |     YES     |      None      |
+---------------------------------------------------+------------------+-------------+----------------+
 * postgresql://root:***@127.0.0.1:5432/chicago
22 rows affected.
chicago_crime_data
+----------------------+------------------+-------------+----------------+
|     column_name      |    data_type     | is_nullable | column_default |
+----------------------+------------------+-------------+----------------+
|          id          |      bigint      |     YES     |      None      |
|       domestic       |     boolean      |     YES     |      None      |
|         beat         |      bigint      |     YES     |      None      |
|       district       |      bigint      |     YES     |      None      |
|         ward         |      bigint      |     YES     |      None      |
|    community_area    |      bigint      |     YES     |      None      |
|     x_coordinate     | double precision |     YES     |      None      |
|     y_coordinate     | double precision |     YES     |      None      |
|         year         |      bigint      |     YES     |      None      |
|       latitude       | double precision |     YES     |      None      |
|      longitude       | double precision |     YES     |      None      |
|        arrest        |     boolean      |     YES     |      None      |
|     case_number      |       text       |     YES     |      None      |
|         date         |       text       |     YES     |      None      |
|        block         |       text       |     YES     |      None      |
|         iucr         |       text       |     YES     |      None      |
|     primary_type     |       text       |     YES     |      None      |
|     description      |       text       |     YES     |      None      |
| location_description |       text       |     YES     |      None      |
|       fbi_code       |       text       |     YES     |      None      |
|       location       |       text       |     YES     |      None      |
|      updated_on      |       text       |     YES     |      None      |
+----------------------+------------------+-------------+----------------+

In [ ]:
#observo algunas columnas en comun entre las tablas, por ejempo location en 'school_chicago' y tambien en 'chicago_crime_data'
#intuyo que hay una correlacion entre la variable 'school_chicago.average_student_attendance' y la variable 'chicago_crime_data.arrest'.
#ambas pueden estar relacionadas por la variable 'location', comun a ambas tablas

### Problemas interesantes

2- List community area names and numbers with per capita income less than 11000.

In [10]:
%%sql

SELECT community_area_name, ca FROM chicago_socioeconomic_data
    WHERE per_capita_income_ < 11000;

 * postgresql://root:***@127.0.0.1:5432/chicago
4 rows affected.

[('West Garfield Park', 26.0),
 ('South Lawndale', 30.0),
 ('Fuller Park', 37.0),
 ('Riverdale', 54.0)]

3- List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [12]:
%sql SELECT * FROM chicago_crime_data LIMIT 10;

 * postgresql://root:***@127.0.0.1:5432/chicago
10 rows affected.

[(13745112, 'JJ144775', '2025-02-09T00:00:00.000', '113XX S LOWE AVE', '1187', 'DECEPTIVE PRACTICE', 'STATE BENEFITS FRAUD', 'RESIDENCE', False, False, 2233, 22, 21, 49, '11', 1174005.0, 1829669.0, 2025, '2025-02-16T15:41:59.000', 41.688013138, -87.638609208, '\n,  \n(41.688013138, -87.638609208)'),
 (13744488, 'JJ144220', '2025-02-09T00:00:00.000', '040XX N CICERO AVE', '0860', 'THEFT', 'RETAIL THEFT', 'CONVENIENCE STORE', False, False, 1624, 16, 45, 15, '06', 1143644.0, 1926627.0, 2025, '2025-02-16T15:41:59.000', 41.954698652, -87.747338823, '\n,  \n(41.954698652, -87.747338823)'),
 (13744502, 'JJ144167', '2025-02-09T00:00:00.000', '023XX N NORDICA AVE', '0486', 'BATTERY', 'DOMESTIC BATTERY SIMPLE', 'RESIDENCE', True, True, 2512, 25, 29, 18, '08B', 1128700.0, 1914859.0, 2025, '2025-02-16T15:41:59.000', 41.922673111, -87.802544263, '\n,  \n(41.922673111, -87.802544263)'),
 (13749436, 'JJ150268', '2025-02-09T00:00:00.000', '014XX N SANDBURG TER', '1153', 'DECEPTIVE PRACTICE', 'FINANCIAL IDENTITY THEFT OVER $ 300', 'APARTMENT', False, False, 1821, 18, 2, 8, '11', None, None, 2025, '2025-02-16T15:41:59.000', None, None, None),
 (13745190, 'JJ145055', '2025-02-09T00:00:00.000', '013XX S HARDING AVE', '1150', 'DECEPTIVE PRACTICE', 'CREDIT CARD FRAUD', 'STREET', False, False, 1011, 10, 24, 29, '11', 1150263.0, 1893416.0, 2025, '2025-02-16T15:41:59.000', 41.8634377, -87.723873589, '\n,  \n(41.8634377, -87.723873589)'),
 (13744046, 'JJ143609', '2025-02-09T00:00:00.000', '047XX S HERMITAGE AVE', '1365', 'CRIMINAL TRESPASS', 'TO RESIDENCE', 'RESIDENCE', True, True, 931, 9, 15, 61, '26', 1165479.0, 1873239.0, 2025, '2025-02-16T15:41:59.000', 41.807759957, -87.668589943, '\n,  \n(41.807759957, -87.668589943)'),
 (13744250, 'JJ143928', '2025-02-09T00:00:00.000', '087XX S MAY ST', '2820', 'OTHER OFFENSE', 'TELEPHONE THREAT', 'APARTMENT', False, True, 2222, 22, 21, 71, '08A', 1170180.0, 1846888.0, 2025, '2025-02-16T15:41:59.000', 41.735348493, -87.652113479, '\n,  \n(41.735348493, -87.652113479)'),
 (13744183, 'JJ143799', '2025-02-09T00:00:00.000', '018XX N MILWAUKEE AVE', '0620', 'BURGLARY', 'UNLAWFUL ENTRY', 'APARTMENT', False, False, 1434, 14, 32, 22, '05', 1161022.0, 1912110.0, 2025, '2025-02-16T15:41:59.000', 41.914519246, -87.683858576, '\n,  \n(41.914519246, -87.683858576)'),
 (13744895, 'JJ144631', '2025-02-09T00:00:00.000', '030XX W 23RD ST', '1320', 'CRIMINAL DAMAGE', 'TO VEHICLE', 'STREET', False, False, 1033, 10, 24, 30, '14', 1156533.0, 1888567.0, 2025, '2025-02-16T15:41:59.000', 41.850007064, -87.700987857, '\n,  \n(41.850007064, -87.700987857)'),
 (13748971, 'JJ149574', '2025-02-09T00:00:00.000', '014XX W JONQUIL TER', '0820', 'THEFT', '$500 AND UNDER', 'ALLEY', False, False, 2422, 24, 49, 1, '06', 1165250.0, 1950993.0, 2025, '2025-02-16T15:41:59.000', 42.021126777, -87.667214932, '\n,  \n(42.021126777, -87.667214932)')]

In [14]:
%sql SELECT DISTINCT(primary_type) FROM chicago_crime_data;

 * postgresql://root:***@127.0.0.1:5432/chicago
24 rows affected.

[('BURGLARY',),
 ('INTIMIDATION',),
 ('SEX OFFENSE',),
 ('ROBBERY',),
 ('PUBLIC PEACE VIOLATION',),
 ('CRIMINAL SEXUAL ASSAULT',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('WEAPONS VIOLATION',),
 ('LIQUOR LAW VIOLATION',),
 ('INTERFERENCE WITH PUBLIC OFFICER',),
 ('CONCEALED CARRY LICENSE VIOLATION',),
 ('OFFENSE INVOLVING CHILDREN',),
 ('DECEPTIVE PRACTICE',),
 ('THEFT',),
 ('ARSON',),
 ('HOMICIDE',),
 ('STALKING',),
 ('ASSAULT',),
 ('BATTERY',),
 ('CRIMINAL TRESPASS',),
 ('MOTOR VEHICLE THEFT',),
 ('OTHER OFFENSE',),
 ('KIDNAPPING',)]

In [15]:
%sql SELECT DISTINCT(description) FROM chicago_crime_data;

 * postgresql://root:***@127.0.0.1:5432/chicago
117 rows affected.

[('FORGERY',),
 ('OBSTRUCTING IDENTIFICATION',),
 ('FINANCIAL IDENTITY THEFT OVER $ 300',),
 ('OTHER',),
 ('POSSESS - SYNTHETIC DRUGS',),
 ('UNLAWFUL POSSESSION - AMMUNITION',),
 ('HARASSMENT BY ELECTRONIC MEANS',),
 ('VIOLATION OF CIVIL NO CONTACT ORDER',),
 ('FIRST DEGREE MURDER',),
 ('TO RESIDENCE',),
 ('AGGRAVATED - OTHER',),
 ('OVER $500',),
 ('MANUFACTURE / DELIVER - CRACK',),
 ('BY FIRE',),
 ('POSSESSION OF BURGLARY TOOLS',),
 ('ATTEMPT FORCIBLE ENTRY',),
 ('ATTEMPT THEFT',),
 ('FORCIBLE ENTRY',),
 ('LIQUOR LICENSE VIOLATION',),
 ('LICENSE VIOLATION',),
 ('PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY',),
 ('THEFT OF LABOR / SERVICES',),
 ('AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY',),
 ('$500 AND UNDER',),
 ('CREDIT CARD FRAUD',),
 ('RECKLESS FIREARM DISCHARGE',),
 ('BOMB THREAT',),
 ('GUN OFFENDER - ANNUAL REGISTRATION',),
 ('CHILD ABUSE',),
 ('COUNTERFEITING DOCUMENT',),
 ('UNLAWFUL ENTRY',),
 ('HARASSMENT BY TELEPHONE',),
 ('AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',),
 ('CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',),
 ('UNLAWFUL USE - OTHER FIREARM',),
 ('CRIMINAL DEFACEMENT',),
 ('MANUFACTURE / DELIVER - CANNABIS OVER 10 GRAMS',),
 ('RETAIL THEFT',),
 ('SOLICIT NARCOTICS ON PUBLIC WAY',),
 ('ENDANGERING LIFE / HEALTH OF CHILD',),
 ('WIC FRAUD',),
 ('POSSESS FIREARM / AMMUNITION - NO FOID CARD',),
 ('THEFT FROM MOTOR VEHICLE',),
 ('POSSESS - CANNABIS MORE THAN 30 GRAMS',),
 ('AGGRAVATED - OTHER DANGEROUS WEAPON',),
 ('STATE BENEFITS FRAUD',),
 ('ATTEMPT ARSON',),
 ('ILLEGAL USE CASH CARD',),
 ('OTHER OFFENSE',),
 ('FROM BUILDING',),
 ('FRAUD OR CONFIDENCE GAME',),
 ('POSSESS - HALLUCINOGENS',),
 ('HOME INVASION',),
 ('BURGLARY FROM MOTOR VEHICLE',),
 ('AGGRAVATED - KNIFE / CUTTING INSTRUMENT',),
 ('AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',),
 ('POCKET-PICKING',),
 ('AGGRAVATED OF A SENIOR CITIZEN',),
 ('PUBLIC INDECENCY',),
 ('SIMPLE',),
 ('POSSESS - PCP',),
 ('POSSESS - HEROIN (WHITE)',),
 ('THEFT BY LESSEE, MOTOR VEHICLE',),
 ('STRONG ARM - NO WEAPON',),
 ('AGGRAVATED POLICE OFFICER - OTHER DANGEROUS WEAPON',),
 ('DOMESTIC BATTERY SIMPLE',),
 ('ATTEMPT NON-AGGRAVATED',),
 ('FALSE / STOLEN / ALTERED TRP',),
 ('ILLEGAL CONSUMPTION BY MINOR',),
 ('INTIMIDATION',),
 ('THEFT / RECOVERY - CYCLE, SCOOTER, BIKE NO VIN',),
 ('NON-AGGRAVATED',),
 ('OTHER VEHICLE OFFENSE',),
 ('PURSE-SNATCHING',),
 ('TO PROPERTY',),
 ('AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY',),
 ('GUN OFFENDER - DUTY TO REGISTER',),
 ('AGGRAVATED',),
 ('UNLAWFUL POSSESSION - HANDGUN',),
 ('UNLAWFUL USE OF A COMPUTER',),
 ('NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',),
 ('FOUND SUSPECT NARCOTICS',),
 ('VIOLATE ORDER OF PROTECTION',),
 ('POSSESS - COCAINE',),
 ('POSSESS - CANNABIS 30 GRAMS OR LESS',),
 ('AGGRAVATED - HANDGUN',),
 ('CHILD ABANDONMENT',),
 ('POSSESS - BARBITURATES',),
 ('RECKLESS CONDUCT',),
 ('AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',),
 ('AGGRAVATED POLICE OFFICER - HANDGUN',),
 ('OTHER CRIME AGAINST PERSON',),
 ('POSSESS - CRACK',),
 ('FINANCIAL IDENTITY THEFT $300 AND UNDER',),
 ('ARMED - HANDGUN',),
 ('CRIMINAL SEXUAL ABUSE',),
 ('COUNTERFEIT CHECK',),
 ('VEHICLE TITLE / REGISTRATION OFFENSE',),
 ('TO LAND',),
 ('POSSESSION OF DRUG EQUIPMENT',),
 ('RESIST / OBSTRUCT / DISARM OFFICER',),
 ('IMPERSONATION',),
 ('TO VEHICLE',),
 ('AGGRAVATED - HANDS, FISTS, FEET, NO / MINOR INJURY',),
 ('UNLAWFUL POSSESSION - OTHER FIREARM',),
 ('THEFT OF LOST / MISLAID PROPERTY',),
 ('AUTOMOBILE',),
 ('SEX OFFENDER - FAIL TO REGISTER',),
 ('TELEPHONE THREAT',),
 ('THEFT / RECOVERY - AUTOMOBILE',),
 ('AGGRAVATED - HANDS, FISTS, FEET, SERIOUS INJURY',),
 ('ATTEMPT STRONG ARM - NO WEAPON',),
 ('ATTEMPT - AUTOMOBILE',),
 ('OTHER CRIME INVOLVING PROPERTY',),
 ('POSSESS - HEROIN (BLACK TAR)',),
 ('ATTEMPT - FINANCIAL IDENTITY THEFT',),
 ('VEHICULAR HIJACKING',)]

In [25]:
#%sql SELECT * FROM chicago_crime_data WHERE primary_type LIKE '%CHILD%';
%sql SELECT * FROM chicago_crime_data WHERE primary_type LIKE '%CHILD%' OR description LIKE '%CHILD%';

 * postgresql://root:***@127.0.0.1:5432/chicago
6 rows affected.

[(13743968, 'JJ143507', '2025-02-08T22:10:00.000', '132XX S GREENWOOD AVE', '1755', 'OFFENSE INVOLVING CHILDREN', 'CHILD ABANDONMENT', 'STREET', False, True, 533, 5, 10, 54, '20', 1186022.0, 1818065.0, 2025, '2025-02-16T15:41:59.000', 41.655895809, -87.594980408, '\n,  \n(41.655895809, -87.594980408)'),
 (13744424, 'JJ143921', '2025-02-08T14:00:00.000', '065XX S MARSHFIELD AVE', '1751', 'OFFENSE INVOLVING CHILDREN', 'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER', 'RESIDENCE', False, True, 725, 7, 15, 67, '17', 1166452.0, 1861305.0, 2025, '2025-02-16T15:41:59.000', 41.774990905, -87.665361322, '\n,  \n(41.774990905, -87.665361322)'),
 (13749651, 'JJ150545', '2025-02-08T00:00:00.000', '019XX W 17TH ST', '1752', 'OFFENSE INVOLVING CHILDREN', 'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER', 'APARTMENT', False, True, 1234, 12, 25, 31, '17', None, None, 2025, '2025-02-16T15:41:59.000', None, None, None),
 (13745439, 'JJ142407', '2025-02-07T20:40:00.000', '022XX E 103RD ST', '1780', 'OFFENSE INVOLVING CHILDREN', 'OTHER OFFENSE', 'POLICE FACILITY / VEHICLE PARKING LOT', False, False, 434, 4, 7, 51, '20', 1192874.0, 1837123.0, 2025, '2025-02-15T15:41:40.000', 41.708029389, -87.569290282, '\n,  \n(41.708029389, -87.569290282)'),
 (13743063, 'JJ142374', '2025-02-07T18:00:00.000', '010XX N LAWNDALE AVE', '1710', 'OFFENSE INVOLVING CHILDREN', 'ENDANGERING LIFE / HEALTH OF CHILD', 'APARTMENT', False, True, 1112, 11, 27, 23, '20', 1151526.0, 1906602.0, 2025, '2025-02-15T15:41:40.000', 41.899596799, -87.718890614, '\n,  \n(41.899596799, -87.718890614)'),
 (13747190, 'JJ147355', '2025-02-07T10:00:00.000', '014XX S CHRISTIANA AVE', '1750', 'OFFENSE INVOLVING CHILDREN', 'CHILD ABUSE', 'SCHOOL - PUBLIC BUILDING', False, False, 1021, 10, 24, 29, '08B', 1154267.0, 1892829.0, 2025, '2025-02-15T15:41:40.000', 41.861747967, -87.709190774, '\n,  \n(41.861747967, -87.709190774)')]

4- List all kidnapping crimes involving a child?

In [28]:
%%sql 
--SELECT * FROM chicago_crime_data WHERE primary_type = 'KIDNAPPING'
SELECT * FROM chicago_crime_data 
    WHERE primary_type = 'KIDNAPPING' AND description LIKE '%CHILD%';

 * postgresql://root:***@127.0.0.1:5432/chicago
0 rows affected.

[]

5- List the kind of crimes that were recorded at schools. (No repetitions)

In [32]:
%%sql
SELECT DISTINCT(location), community_area, block FROM chicago_crime_data
    WHERE location_description LIKE '%SCHOOL%';

 * postgresql://root:***@127.0.0.1:5432/chicago
15 rows affected.

[('\n,  \n(41.692041778, -87.665923635)', 75, '017XX W PRYOR AVE'),
 ('\n,  \n(41.695281455, -87.642470829)', 75, '109XX S HALSTED ST'),
 ('\n,  \n(41.73928511, -87.625536799)', 44, '085XX S LAFAYETTE AVE'),
 ('\n,  \n(41.750018538, -87.558406932)', 46, '027XX E 80TH ST'),
 ('\n,  \n(41.774945985, -87.586321063)', 42, '066XX S STONY ISLAND AVE'),
 ('\n,  \n(41.803201891, -87.72198373)', 57, '049XX S ARCHER AVE'),
 ('\n,  \n(41.823798151, -87.619756522)', 35, '002XX E PERSHING RD'),
 ('\n,  \n(41.836982572, -87.718642232)', 30, '037XX W 31ST ST'),
 ('\n,  \n(41.861747967, -87.709190774)', 29, '014XX S CHRISTIANA AVE'),
 ('\n,  \n(41.864217865, -87.702173146)', 29, '013XX S SACRAMENTO DR'),
 ('\n,  \n(41.877999103, -87.723948226)', 26, '039XX W ADAMS ST'),
 ('\n,  \n(41.889096979, -87.705130816)', 23, '004XX N TROY ST'),
 ('\n,  \n(41.903509764, -87.717806169)', 23, '012XX N MONTICELLO AVE'),
 ('\n,  \n(41.946542477, -87.736084376)', 16, '036XX N MILWAUKEE AVE'),
 ('\n,  \n(41.965457044, -87.652995284)', 3, '009XX W WILSON AVE')]

6- List the type of schools along with the average safety score for each type.

In [38]:
%%sql
SELECT DISTINCT(elementary_or_high_school), AVG(safety_score)
    FROM school_chicago GROUP BY elementary_or_high_school;

 * postgresql://root:***@127.0.0.1:5432/chicago
3 rows affected.

[('ES', 49.52038369304557), ('HS', 49.62352941176471), ('MS', 48.0)]

7- List 5 community areas with highest % of households below poverty line

In [39]:
%%sql
SELECT ca FROM chicago_socioeconomic_data
    ORDER BY percent_households_below_poverty DESC LIMIT 5;

 * postgresql://root:***@127.0.0.1:5432/chicago
5 rows affected.

[(54.0,), (37.0,), (68.0,), (29.0,), (27.0,)]

8- Which community area is most crime prone? Display the coumminty area number only.

In [54]:
res = %sql SELECT community_area, COUNT(community_area) AS cant_crim \
        FROM chicago_crime_data \
            GROUP BY community_area ORDER BY cant_crim DESC LIMIT 1;
print(res)
#communitry area most crimes es
ca_mc = res[0][0]
print(ca_mc)

 * postgresql://root:***@127.0.0.1:5432/chicago
1 rows affected.
+----------------+-----------+
| community_area | cant_crim |
+----------------+-----------+
|       25       |     50    |
+----------------+-----------+
25

9 - Use a sub-query to find the name of the community area with highest hardship index

In [51]:
%%sql
SELECT community_area_name FROM chicago_socioeconomic_data
    WHERE hardship_index = (SELECT MAX(hardship_index) FROM chicago_socioeconomic_data)

 * postgresql://root:***@127.0.0.1:5432/chicago
1 rows affected.

[('Riverdale',)]

10- Use a sub-query to determine the Community Area Name with most number of crimes?

In [55]:
%%sql
SELECT community_area_name FROM chicago_socioeconomic_data
    WHERE ca = :ca_mc;

 * postgresql://root:***@127.0.0.1:5432/chicago
1 rows affected.

[('Austin',)]